version: 2.1

jobs:
  cypress-run:
    docker:
      - image: cypress/included:15.7.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run Cypress tests
          command: npx cypress run

workflows:
  version: 2
  test:
    jobs:
      - cypress-run

